### ISSUE TITLE
pyperscan is slower than python-hyperscan

### ISSUE THREAD

**Issue by agateau-gg** [vlaci/pyperscan#29]
We currently use the python-hyperscan bindings, but are evaluating Pyperscan because of its support for ARM architecture. The problem we face however is that we find Pyperscan to be roughly 50% slower than python-hyperscan.

I attach a [small script][script] to demonstrate our problem. The script scans a tree of files for common Python keywords using both bindings. The scan is repeated 10 times and results are compared to ensure they are the same.

Here are the results I get when running it on an installed Django package, using x86-64 Linux machine:

```
$ scanbench $VIRTUAL_ENV/lib/python3.10/site-packages/django 
python-hyperscan: 0.0464 s
pyperscan       : 0.0759 s
```

Is this a known issue of Pyperscan, or am I using it wrong?

[script]: https://github.com/vlaci/pyperscan/files/13561917/scanbench.zip

**Comment by vlaci** [comment]
~My only idea is that vectorscan's x86 build is slower which is how the pypi binaries are built~

**EDIT**: Nope

**Comment by vlaci** [comment]
I've dug a bit deeper:
- embarasingly the binaries on pypi are not built with optimizations  
  I'll fix it in the next patch release.
- you are building the database at every iteration when using pyperscan  
  I understand, that in your case, you want to decouple the context from the db.
  
  With this code, the performance difference comes from a the extra indirection introduced by the callback:
  
  ```python
  class Pyperscanner:
      name = "pyperscan"

      def __init__(self):
          patterns = [
              ps.Pattern(x[0], ps.Flag.DOTALL, ps.Flag.SINGLEMATCH, tag=x[1])
              for x in PATTERNS_AND_IDS
          ]
          self.db = ps.BlockDatabase(*patterns)
          self.results: ScanResults = None
          def append(id):
              self.results.append(id)
          self.scanner = self.db.build(append, Pyperscanner._on_match)

      @staticmethod
      def _on_match(append, id, start_, stop_):
          append(id)
          return ps.Scan.Continue

      def scan(self, content) -> ScanResults:
          self.results = []
          self.scanner.scan(content)
          return self.results
  ```

  ```
  python-hyperscan: 0.0558 s
  pyperscan       : 0.0605 s
  ```
  
  If "break" the code to use a global list, the difference becomes negligable:
  ```
  python-hyperscan: 0.0546 s
  pyperscan       : 0.0575 s
  ```

**Comment by agateau-gg** [comment]
Thanks a lot for your detailed answer!

I had tried to avoid creating the database on each scan before, but it did not work because I did not thought about passing a callback to `build()` instead of a list.

Now my tests shows pyperscan is as fast and even sometimes faster than python-hyperscan!

**Comment by agateau-gg** [comment]
For the record: turns out the reason I wrote the code as I did was because I could not share the Scanner between threads: it would fail like that:

```
thread '<unnamed>' panicked at 'assertion failed: `(left == right)`
  left: `ThreadId(2)`,
  right: `ThreadId(1)`: pyperscan::python::extension::PyBlockScanner is unsendable, but sent to another thread!',
  /root/(...)/pyo3-0.17.3/src/impl_/pyclass.rs:1056:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Storing the Scanner instance in thread-local storage "fixed" that.

**Comment by vlaci** [comment]
I think this can be improved upon, as there is a way to share databases between threads

**Comment by agateau-gg** [comment]
Oh, that would be great.
